DROP TABLE IF EXISTS employees, departments, projects, department_employees, projects_employees;

CREATE TABLE IF NOT EXISTS employees
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(100),
    lastname  VARCHAR(100),
    salary    INTEGER
);

CREATE TABLE IF NOT EXISTS departments
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS projects
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS department_employees
(
    department_id BIGINT REFERENCES departments (id) ON DELETE CASCADE NOT NULL,
    employee_id   BIGINT REFERENCES employees (id) ON DELETE CASCADE   NOT NULL,
    PRIMARY KEY (department_id, employee_id),
    CONSTRAINT UQ_DEPARTMENT_WITH_EMPLOYEE UNIQUE (department_id, employee_id)
);

CREATE TABLE IF NOT EXISTS projects_employees
(
    project_id  BIGINT REFERENCES projects (id) ON DELETE CASCADE  NOT NULL,
    employee_id BIGINT REFERENCES employees (id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (project_id, employee_id),
    CONSTRAINT UQ_PROJECT_WITH_EMPLOYEE UNIQUE (project_id, employee_id)
);
